[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Role of Empowerment in Conflict Resolution: Providing Tools and Resources for Effective Communication and Mediation"
